### ISSUE TITLE
Some GeoJSONs won't show in the Debug Tool

### ISSUE THREAD

**Issue by manassra** [mapbox/geojson-vt#100]
For some reason, some GeoJSONs won't show up in the debug tool even though the console log statement showed that the file was parsed and tiled successfully:

Input file: https://data.sfgov.org/Geographic-Locations-and-Boundaries/San-Francisco-Basemap-Street-Centerlines/7hfy-8sz8/data

**Console**
![image](https://user-images.githubusercontent.com/1332450/38642697-ae133f34-3d8f-11e8-9700-7a6249fe0a20.png)

**Debug Tool**
![image](https://user-images.githubusercontent.com/1332450/38642710-b6babe50-3d8f-11e8-9840-e45062ea41b0.png)

Is this a bug?

**Comment by asheemmamoowala** [comment]
@manassra the data you are working with is not visible at lower zooms. Zoom in on the appropriate tiles to view it in the debug page. 

![screen shot 2018-04-11 at 2 46 21 pm](https://user-images.githubusercontent.com/11619675/38644982-60334b1c-3d97-11e8-8d59-edc47747e3e8.png)
