### ISSUE TITLE
Max call stack size error on a certain input

### ISSUE THREAD

**Issue by mourner** [mapbox/geojson-vt#104]
Originally reported at https://github.com/mapbox/mapbox-gl-js/issues/6086#issuecomment-394814754

Minimal test case for Node v8:

```js
const geojsonvt = require('geojson-vt');

const coords = [];
for (let i = 0; i < 1400; i++) {
    coords.push([0.0, 0.0], [1.0, 0.0], [1.0, 1.0], [0.0, 1.0]);
}

const data = {
    "type": "LineString",
    "coordinates": coords
};

geojsonvt(data);
```

cc @JamesChevalier

**Comment by JamesChevalier** [comment]
Let me know if you would like any real world testing. I'm happy to throw around beta software to see if https://citystrides.com/users/5560/map loads properly with Safari or Chrome on a Mac (where I originally noticed the issue).

**Comment by district10** [comment]
Why `mid` is `(last-first)/2`? Shouldn't it be `(first+last)/2`?

(or `first + (last-first)>>1` for avoiding overflow.)

Related code:

- https://github.com/mapbox/geojson-vt-cpp/blob/master/include/mapbox/geojsonvt/simplify.hpp#L37-L60
- https://github.com/mapbox/geojson-vt/blob/main/src/simplify.js#L6-L32

**Comment by mourner** [comment]
@district10 nice catch, likely a mistake (although it shouldn't affect correctness of the output at least). Want to PR a fix?

**Comment by district10** [comment]
@mourner Sure. Two PRs created.
