### ISSUE TITLE
function projectX(x) and projectY(y) 

### ISSUE THREAD

**Issue by 748448660** [mapbox/geojson-vt#110]
What is the role of function projectX(x) and projectY(y) ? and the coordinate of my geojson file is not latitude and longitude.  It seems that the projectX method don't work.

**Comment by mourner** [comment]
geojson-vt follows the [GeoJSON specification](https://tools.ietf.org/html/rfc7946#section-3.1.1), which states that coordinates must be a pair of longitude/latitude and use the WGS coordinate system.
