### ISSUE TITLE
Add warning for not Number type (debug mode)

### ISSUE THREAD

**Issue by bravecow** [mapbox/geojson-vt#111]
https://github.com/mapbox/geojson-vt/blob/212568da3f383ea4186348dcebcdfc2f1a956c2f/src/index.js#L154

If x, y, z are string type, getTile returns null. Wasted a lot of time to find it out 🙄 

Or at least please add it to README.
Thanks.

**Comment by andrewharvey** [comment]
oh boy, I too spent a lot of time scratching my head wondering why this wasn't working. For the most part JS will naturally convert to a number for most of the code when doing arithmetic, except at 

https://github.com/mapbox/geojson-vt/blob/aa2522b2820a7ed13dc17b38e703baeac47cb6cf/src/index.js#L194-L196

It decides to concatenate numbers first, so the results are completely messed up.

I've proposed #128 as a fix, I'd rather getTile just fix up any numbers passed as strings.

**Comment by bravecow** [comment]
👍(personally, I prefer more obviously conversion with `Number()` 🙄)
