### ISSUE TITLE
Priority of geojson.id is lower than options.generateId

### ISSUE THREAD

**Issue by gorshkov-leonid** [mapbox/geojson-vt#119]
https://github.com/mapbox/geojson-vt/blob/d3bf094b1329dd84dcc8446ba407c9830469b808/src/convert.js#L32

```
    var id = geojson.id;
    if (options.promoteId) {
        id = geojson.properties[options.promoteId];
    } else if (options.generateId) {
        id = index || 0;
    }
```
May be geojson.id should be exclusive?

**Comment by mourner** [comment]
I think this was intentional, so that ids are consistent across the dataset — either fully user-provided, or fully generated by one of the two options (cc @asheemmamoowala). Mixing both doesn't seem like a good idea. @gorshkov-leonid Can you describe your use case in more detail?

**Comment by gorshkov-leonid** [comment]
Ok, I agree. Thank you

**Comment by gorshkov-leonid** [comment]
The case of usage is creation of configuration without extra data. If I want I can add an id, but it is not necessary. 
```
const point1 = {
    id: 0,/*is not necessary in this case, but it can be important to specify concrete id in other cases?*/
    type: "Point", coordinates: randomCoords(1)[0],
    properties: {
        externalId: "point-1",
        label: {
            "label-profile-1": "Label 1",
            "label-profile-2": "Label 2"
        },
        style: {
            "profile-1": {pointColor: "C52C36", pointSubstrate: "droplet", iconUrl: "/geographicalview/images/droplet.png"}
        }
    }
};
```
but I think it can cause mistakes.
