### ISSUE TITLE
Creation of tilecoords, adding memory to tilecoords, never used

### ISSUE THREAD

**Issue by CraigglesO** [mapbox/geojson-vt#129]
Was reading through the source code, and noticed you keep pushing to tilecoords, but you never actually use it, so potentially a lot of memory going to waste...

Not really a terrible issue, just an enhancement if you'd like.

https://github.com/mapbox/geojson-vt/blob/83d5ce8a1668f49fde370c8e8d5e37ee7b880d7b/src/index.js#L25

**Comment by mourner** [comment]
It's a pretty tiny overhead, and it's used externally — `index.tileCoords` is a part of the public API.
