### ISSUE TITLE
How to determine buffer?

### ISSUE THREAD

**Issue by am2222** [mapbox/geojson-vt#142]
Hi,
I am editing leafler vector grid to read my own data from my server, I clip data using `geojson-vt` library. But some of the cells are removed from each tile. VectorGrid plugin developers suggested me to use `buffer` option in geojson-vt but it does not change for values higher than 100. Is there any workarounds to find a solution to this problem?
![SharedScreenshot](https://user-images.githubusercontent.com/4707503/71299637-6794f480-235c-11ea-9a8e-876719a3d961.jpg)

**Comment by slutske22** [comment]
Did you ever find out more about this?  I am running into a similar issue
