### ISSUE TITLE
ESLint couldn't find the config "mourner" to extend from

### ISSUE THREAD

**Issue by schpokatron** [mapbox/geojson-vt#148]
I'm hacking geojson-vt to this down point features at lower levels of detail, and wish to npm publish to test locally. package.json specifies eslintConfig extends "mourner" which is not included in this package.

Would we consider either including this configuration file, or using some preexisting configuration?

**Comment by mourner** [comment]
It's included as a dependency. https://github.com/mapbox/geojson-vt/blob/main/package.json#L26
