### ISSUE TITLE
rounding to the nearest integer

### ISSUE THREAD

**Issue by captain-igloo** [mapbox/geojson-vt#149]
Why are points rounded [here](https://github.com/mapbox/geojson-vt/blob/35f4ad75feed64e80ff2cd02994976c6335859cd/src/transform.js#L39)? Aren't the rounded numbers are less accurate?

Could a configuration option be added to control this behaviour?

My use case - I have a circle as a polygon, when I draw the result from geojson-vt on the canvas it is not as smooth due to the rounding.  See screenshot, the circle on the left is the original, the one on the right has had its coordinates rounded.

![geojson-vt-screenshot](https://user-images.githubusercontent.com/8575674/97512970-ccdf5a80-19ef-11eb-9a42-1369ec61c7c7.png)

**Comment by mourner** [comment]
They are rounded because they should be integers according to the [vector tile specification](https://github.com/mapbox/vector-tile-spec/tree/master/2.1). To increase precision, you need to make the layer `extent` bigger (in geojson-vt, it's 4096 for a tile by default).
