### ISSUE TITLE
Label Cropping and overlap problem

### ISSUE THREAD

**Issue by Meshkipoosh** [mapbox/geojson-vt#153]
Hi,
Labels are cropped at tile boundaries. what is the solution to prevent this? i'm using SLD files to define labels and symbology.

![image](https://user-images.githubusercontent.com/36596027/125161472-d8e30500-e197-11eb-998e-1648474283d7.png)

**Comment by mourner** [comment]
I have no idea, this doesn't appear to be a `geojson-vt` issue and there are no details apart from the screenshot to know what's going on, so I'll have to close.
