### ISSUE TITLE
Strange Clipping issue. 

### ISSUE THREAD

**Issue by ibrierley** [mapbox/geojson-vt#156]
This may be related to the other clipping issue, not sure. I note if I bypass clipping it works ok.
Example geojson..
```
{
    "type": "Feature",
    "geometry": {
        "type": "Polygon",
        "coordinates": [
            [
              [-178, 10],[20, 85],[178, -5]
            ]
        ]
    },
    "style": {
        "stroke-width": "3",
        "fill-opacity": 0.6
    },
    "className": {
        "baseVal": "highway_primary"
    }
}
```
In the demo page, it produces for the top layer, which is ok...
![mapbox github io_geojson-vt_debug_](https://user-images.githubusercontent.com/3901173/173230597-d12fb3b9-1de2-41e4-9a7d-32acbcf792e4.png)

But then if you click on the top right quadrant of the demo page, it gives..

![mapbox github io_geojson-vt_debug_ (1)](https://user-images.githubusercontent.com/3901173/173230652-23ba071f-17ae-46cf-94be-ba8dcddba246.png)

And also seems to add lines on tile boundaries (I can't highlight that on the demo page, as it has tile lines there, but as an example from mine..
![localhost_35709_](https://user-images.githubusercontent.com/3901173/173230694-827d9816-efa2-439b-a83b-550ac554494e.png)

This is the same on this version in Git, and the hosted demo page. (I've also eliminated wrap and simplify to test further)

**Comment by mourner** [comment]
Can you try it with the line string closed (last point the same as the first one), as required by the GeoJSON spec for polygons?

**Comment by ibrierley** [comment]
ok thanks, that kinda makes sense, but there are still odd tile edge lines...(which aren't there if I comment out the clip code. This is the closed triangle.
![localhost_44347_](https://user-images.githubusercontent.com/3901173/173253740-4b15c212-e2b6-4d30-8318-fabcad7675e4.png)

```
{
    "type": "Feature",
    "geometry": {
        "type": "Polygon",
        "coordinates": [
            [
              [-178, 10],[20, 85],[178, -5],[-178, 10]
            ]
        ]
    },
    "style": {
        "stroke-width": "3",
        "fill-opacity": 0.6
    },
    "className": {
        "baseVal": "highway_primary"
    }
}
```

**Comment by ibrierley** [comment]
Just to clarify, thats zoomed into zoom 2 (and thats a screenshot from my version, I think the demo obscures those, as the demo draws borders alongside tile edges anyway.

**Comment by ibrierley** [comment]
Actually, is this just a question of whether it's a filled polygon (as you'd use a linestring for an unfilled one) as geojson probably doesn't? I suspect it's fine isn't it!

**Comment by ibrierley** [comment]
Thanks for the help, the original non-closing of the polygon threw my brain about the problem :).
