### ISSUE TITLE
How to remove redundant vertical and horizontal lines

### ISSUE THREAD

**Issue by nhtlquan** [mapbox/geojson-vt#158]
I using this lib for my project. Draw geoJson to map.
Type of geoJson: MultiPolygon, file: https://drive.google.com/file/d/1SnhqjMAbmWozhuhfVM0GjQHPNwq2ziWn/view?usp=sharing
But has redundant vertical and horizontal lines. 
How to remove it!
Thank

![image](https://user-images.githubusercontent.com/20571358/186892157-dcad9129-0d11-4f9d-a146-48a37f39de05.png)

**Comment by mourner** [comment]
There's no way to remove those. They are artifacts of the polygon clipping algorithm. Basically you're supposed to use a certain buffer around a tile, and then clip each tile to its extent (we do that with WebGL stencil buffer in GL JS, but if you're drawing with something else like SVG, it also supports clipping masks).
