### ISSUE TITLE
Show only one label per featrure

### ISSUE THREAD

**Issue by Meshkipoosh** [mapbox/geojson-vt#163]
Hi, Is it possible to show only one label per feature? Currently, labels are repeated for different parts of a feature in different tiles. I'm using Openlayers.

![Screenshot 2022-12-10 104133](https://user-images.githubusercontent.com/36596027/206837668-59d163ac-8cba-43b1-8036-9269169bb8b0.jpg)

**Comment by mourner** [comment]
You would have to generate label features from input data before feeding it to `geojson-vt` (whose sole purpose is to split data into tiles).
