### ISSUE TITLE
Geojson linestring

### ISSUE THREAD

**Issue by aparzi** [mapbox/geojson-vt#164]
This library support geojson which include linestring only?

thank you

**Comment by mourner** [comment]
Yes

**Comment by aparzi** [comment]
@mourner 
I uploaded a linestring geojson to the debug page but it doesn't render. The geojson file is correct

**Comment by aparzi** [comment]
@mourner 
my problem is that I have to zoom a lot to see the linestrings. Do you know why?

**Comment by mourner** [comment]
@aparzi geojson-vt filters out very small lines as a part of its simplification routine. You can disable the latter by passing `tolerance: 0` in the options.

**Comment by aparzi** [comment]
@mourner thanks. 
Can I attach events (e.g. click) on features rendered by geojson-vt on openlayers?
