### ISSUE TITLE
Rendering huge points

### ISSUE THREAD

**Issue by aparzi** [mapbox/geojson-vt#167]
Hello everyone, I have integrated the library with openlayers. By rendering 300K lines it works correctly, instead with 100/200K points everything freezes up to significantly increase the RAM.  I'm using the library's default options, I've noticed that decreasing the width of the tiles is slightly better but not optimal.  am I doing something wrong?  Do you have any suggestions?

**Comment by aparzi** [comment]
@mourner this issue may be closed.  Could we think of a clustering implementation for the points?  So as not to use two libraries

**Comment by aparzi** [comment]
HI @mourner, what do you think if we introduce clustering for points?

Thanks.

**Comment by mourner** [comment]
Nope, no plans to do this within the scope of this project.
