### ISSUE TITLE
Bug cluster points

### ISSUE THREAD

**Issue by aparzi** [mapbox/geojson-vt#168]
Hi, I'm trying to upload around 200k points but at high zoom these are not clustering. The options are the default ones. Can someone help me?

**Comment by mourner** [comment]
geojson-vt doesn't do clustering. Maybe you're looking for https://github.com/mapbox/supercluster?

**Comment by aparzi** [comment]
@mourner okay thanks. Couldn't you think of a clustering implementation for the points?
