### ISSUE TITLE
How I use geojson-vt in mapbox gl js ,I need some examples!

### ISSUE THREAD

**Issue by gis-lizhi** [mapbox/geojson-vt#169]
why geojson-vt can be used in ol,leaflet etc .but can't used in mapbox gl js? if it can be used in mapbox ,can I get some examples?

**Comment by mourner** [comment]
`geojson-vt` is used in GL JS internally any time you use a GeoJSON source. It was created specifically for this purpose.

**Comment by gis-lizhi** [comment]
ok,I got ,thank you
