### ISSUE TITLE
Incorrect vector tiles for zoom >= 13 for multipolygons

### ISSUE THREAD

**Issue by dnepromell** [mapbox/geojson-vt#177]
Some cutting of vector tiles for these 4 parcels (multipolygons). I tried with different options, but no luck. Demo page looks like not renders at all this example. 

Geojson file: 
[ubombo.json](https://github.com/mapbox/geojson-vt/files/12860654/ubombo.json)

Zoom 14:

<img width="1478" alt="image" src="https://github.com/mapbox/geojson-vt/assets/2462166/16486b4b-bc0c-4bee-bcc8-b2648782f432">

Zoom 13:

<img width="1305" alt="image" src="https://github.com/mapbox/geojson-vt/assets/2462166/dd7c25bf-1fd2-4050-97f6-e0d3d46a13a9">

Zoom <= 12:

<img width="1457" alt="image" src="https://github.com/mapbox/geojson-vt/assets/2462166/7e900c71-eab2-46d9-be46-a5652d8e03fa">

Geojson.io renders parcels correctly:

<img width="1791" alt="image" src="https://github.com/mapbox/geojson-vt/assets/2462166/ec706102-ceaa-4785-a52d-a68ceb74cce6">

**Comment by mourner** [comment]
Sorry for a late response. This is likely because of polygon simplification logic — geojson-vt throws out polygons which are below a certain area threshold. It can be confirmed by passing `tolerance: 0` which disables simplification.
