### ISSUE TITLE
Updatable tiles

### ISSUE THREAD

**Issue by tmcw** [mapbox/geojson-vt#26]
Would it be possible to add an API that adds data into the pyramid of tiles (and potentially removes it, but that might be tougher)? This would make live-data use cases very interesting.

**Comment by mourner** [comment]
Adding data is relatively easy to add I think, the only problem I see will arise if we implement a sophisticated point filtering algorithm like the one described by @ericfischer.

Removing data would require tagging every feature or geometry with ids, but is also possible. Not sure if it can be made fast though.

**Comment by mourner** [comment]
For now I think it's fast enough to just retile everything when you change data, but still may be very useful in future. Do you have any particular live-data cases in mind?

**Comment by incanus** [comment]
I am working on an approach now in [the C++ port]https://github.com/mapbox/mapbox-gl-native/issues/893) for live-adding and changing points and shapes as a means to add annotations to GL. Will report back on what this brings to light.

**Comment by incanus** [comment]
The approach I'm using is to tile newly-added features, then iterate the tiles and add the tiled features over to some master tiles so as to not have to re-tile the existing features. I keep a reference to the added features around so when their corresponding data objects are removed, the features get pulled back off the master tiles. 

Also, in this system, tiles have layers. All points are added to a single point layer, and each shape is added to its own shape layer for overlay rearrangement purposes. 

I'll keep the rest of the progress over in https://github.com/mapbox/mapbox-gl-native/issues/992, but just wanted to share my thinking so far.

**Comment by gmaclennan** [comment]
For mapping large dynamic datasets this would be very useful, at least adding data, for my use case. Any further thoughts on this?

**Comment by tmcw** [comment]
[mapbox-gl-draw](https://github.com/mapbox/mapbox-gl-draw) is another usecase that would benefit a lot from being able to update data.

**Comment by tmcw** [comment]
Wow, this is an old issue :) Seems like everyone's done fine without it for six years, so probably not that vital!
