### ISSUE TITLE
display points in visualization

### ISSUE THREAD

**Issue by jgrundman** [mapbox/geojson-vt#27]
I can't load a geojson file with just points.  Is this supported?

**Comment by mourner** [comment]
It should be, can you provide a small sample GeoJSON that doesn't work?

**Comment by jgrundman** [comment]
It seems to load, but I don't see the points rendered.  Here's a feature collection geojson I'm trying.

{
   "features" : [
      {
         "type" : "Feature",
         "geometry" : {
            "crs" : {
               "type" : "",
               "properties" : null
            },
            "coordinates" : [
               -75.24897766,
               40.24794006
            ],
            "type" : "Point"
         },
         "properties" : {
         }
      },
      {
         "type" : "Feature",
         "geometry" : {
            "crs" : {
               "type" : "",
               "properties" : null
            },
            "coordinates" : [
               -117.00421143,
               33.74253845
            ],
            "type" : "Point"
         },
         "properties" : {
         }
      },
      {
         "type" : "Feature",
         "geometry" : {
            "crs" : {
               "type" : "",
               "properties" : null
            },
            "coordinates" : [
               -90.0715332,
               32.34098053
            ],
            "type" : "Point"
         },
         "properties" : {
         }
      },
      {
         "type" : "Feature",
         "geometry" : {
            "crs" : {
               "type" : "",
               "properties" : null
            },
            "coordinates" : [
               -74.74076843,
               41.07634735
            ],
            "type" : "Point"
         },
         "properties" : {
         }
      },
      {
         "type" : "Feature",
         "geometry" : {
            "crs" : {
               "type" : "",
               "properties" : null
            },
            "coordinates" : [
               -82.45235443,
               43.03158188
            ],
            "type" : "Point"
         },
         "properties" : {
         }
      },
      {
         "type" : "Feature",
         "geometry" : {
            "crs" : {
               "type" : "",
               "properties" : null
            },
            "coordinates" : [
               -122.29306793,
               47.38481903
            ],
            "type" : "Point"
         },
         "properties" : {
         }
      },
      {
         "type" : "Feature",
         "geometry" : {
            "crs" : {
               "type" : "",
               "properties" : null
            },
            "coordinates" : [
               -99.11850739,
               30.06886101
            ],
            "type" : "Point"
         },
         "properties" : {
         }
      },
      {
         "type" : "Feature",
         "geometry" : {
            "crs" : {
               "type" : "",
               "properties" : null
            },
            "coordinates" : [
               -94.17739868,
               36.1736412
            ],
            "type" : "Point"
         },
         "properties" : {
         }
      },
      {
         "type" : "Feature",
         "geometry" : {
            "crs" : {
               "type" : "",
               "properties" : null
            },
            "coordinates" : [
               -74.16268921,
               40.62718964
            ],
            "type" : "Point"
         },
         "properties" : {
         }
      },
      {
         "type" : "Feature",
         "geometry" : {
            "crs" : {
               "type" : "",
               "properties" : null
            },
            "coordinates" : [
               -81.5929184,
               34.2838974
            ],
            "type" : "Point"
         },
         "properties" : {
         }
      }
   ],
   "type" : "FeatureCollection"
}

**Comment by mourner** [comment]
This looks like an omission in the debug viz page, not a shortcoming of the algorithm.

**Comment by ammont82** [comment]
I need to display 7000 points in visualitzation also. Is it possible? I try to use:

ctx.beginPath();
ctx.arc(features[i].geometry.x,features[i].geometry.y,40,0,2*Math.PI);
ctx.stroke();

But not work.

**Comment by ammont82** [comment]
I can display points. The code is:

 function drawTile() {

            var tile = tileIndex.getTile(z, x, y);

            if (!tile) {
                console.log('tile empty');
                zoomOut();
                return;
            }

            // console.log('z%d-%d-%d: %d points of %d', z, x, y, tile.numSimplified, tile.numPoints);
            // console.time('draw');

            ctx.clearRect(0, 0, height, height);

            var features = tile.features;

            ctx.strokeStyle = 'red';
            ctx.fillStyle = 'rgba(255,0,0,0.05)';

            for (var i = 0; i < features.length; i++) {
                var feature = features[i],
                    typeChanged = type !== feature.type,
                    type = feature.type;

                ctx.beginPath();
               if (type==1){
                  var p=feature.geometry;
                  ctx.arc(p[0][0]/ 16.0,p[0][1]/ 16.0,4,0,2*Math.PI);
               }
               else{
                for (var j = 0; j < feature.geometry.length; j++) {
                    var ring = feature.geometry[j];

                    for (var k = 0; k < ring.length; k++) {
                        var p = ring[k];
                        if (k) ctx.lineTo(p[0] * ratio + pad, p[1] * ratio + pad);
                        else ctx.moveTo(p[0] * ratio + pad, p[1] * ratio + pad);
                    }
                }
                }
                if (type === 3) ctx.fill('evenodd');
                ctx.stroke();
            }
            drawGrid();

            // console.timeEnd('draw');
        }

**Comment by mourner** [comment]
Fixed in https://github.com/mapbox/geojson-vt/commit/3e1b2040dc4d4e9af6aba9f64f1a046174751143

**Comment by incanus** [comment]
Nice! I recently added this to [my intermediary Swift port](https://github.com/incanus/geojsonvt.swift/commit/4fd8f2080e3105b206f1ecd98afbbf17bb1aa8a7) as well.
