### ISSUE TITLE
Option to encode vector tiles into pbfs

### ISSUE THREAD

**Issue by mourner** [mapbox/geojson-vt#28]
Related: https://github.com/mapbox/vector-tile-js/issues/25

**Comment by vespakoen** [comment]
:+1: Any hints on how the json is encoded? or a link to the code where it parses the pbf in mapbox-gl-js perhaps?

**Comment by anandthakker** [comment]
A first cut at this is done here: https://github.com/anandthakker/vt-pbf

**Comment by chriswhong** [comment]
Hi all, I just put this together, it builds a static tile pyramid of vector tiles from a geojson file, using geojson-vt and vt-pbf: https://github.com/NYCPlanning/geojson2mvt

**Comment by mourner** [comment]
Closing here — I think having the tool for that in a separate repo makes sense.
