### ISSUE TITLE
Support different tile sizes

### ISSUE THREAD

**Issue by nofarius** [mapbox/geojson-vt#35]
If you create a canvas tile layer in Leaflet using a tile size other than 256 then the tile indexes within geojson-vt are no longer valid.

For example if you create a canvas tile layer in Leaflet using a tile size of 512:
```javascript
var tiles = new geojsonvt(geoJsonFeatureCollection);

var canvasTile = L.tileLayer.canvas({
    tileSize: 512
});

canvasTile.drawTile = function(canvas, tilePoint, zoom) {
    ...
    var tile = tiles.getTile(zoom, tilePoint.x, tilePoint.y);
   ...
}
```
When the drawCanvasTile function is called the tilePoint x and y values are different based on the tile size, though the getTile function always expects it to be an x and y value that corresponds to a tile size of 256. The below table gives example values based on tile size of x and y

 tilePoint  | 256  | 512  | getTile expects
---|------|------|-----------------
 x | 3500 | 1750 | 3500
 y | 3600 | 1800 | 3600

**Comment by mourner** [comment]
I don't think that's a problem in geojson-vt. It assumes the first tile is always `z0-0-0` no matter what size is used. In Leaflet on the other hand, you have to use a `zoomOffset` option to account for that.
