### ISSUE TITLE
Retina display blurry vector tiles

### ISSUE THREAD

**Issue by dkuzhanov** [mapbox/geojson-vt#37]
Hi @mourner,
First of all, thanks for this awesome library!

quick question: I've managed to set up an application that uses geojson vt together with canvas (similar to this example http://bl.ocks.org/Sumbera/raw/c67e5551b21c68dc8299/ ) and have troubles adjusting it for retina displays.
Is there an approach/set of settings I should use in order to make it look good on retina?

thanks!

**Comment by mourner** [comment]
`geojson-vt` produces data, it doesn't draw anything. GH issues are for bug reports, not for support requests. Please avoid creating issues like this.

Here's how you can go about Retina: https://github.com/mapbox/geojson-vt/blob/master/debug/viz.js#L24-L30

**Comment by dkuzhanov** [comment]
Thanks a lot, Vald! I apologise for creating an extra issue here. 
Your solution worked perfectly!

**Comment by mourner** [comment]
You're welcome!
