### ISSUE TITLE
Limit the size of the tile cache

### ISSUE THREAD

**Issue by aaronlidman** [mapbox/geojson-vt#38]
`this.tiles` grows as you render tiles and this causes memory issues when rendering more than a couple hundred tiles on the server.

Having something like an LRU cache, maybe configureable in size?, would be ideal to get around this.

cc @mourner

**Comment by aaronlidman** [comment]
Bringing this over from chat:
>@aaronlidman: I’d love to hear more about your use case, e.g. how you get these tiles, how often they’re updated and how they’re used afterwards

We're tiling data streams that update every few minutes.

To start we need to render every known feature, a couple million, and then with each update we rerender the tiles that cover the features that changed, tens of thousands.

Ultimately, if possible, all tiles will get pushed to mapbox.com as a [serialtile](https://github.com/mapbox/serialtiles-spec).

**Comment by mourner** [comment]
Is this still relevant after recent fixes to memory footprint? I would try to keep things as simple as possible in geojson-vt if there's no immediate need for LRU caching.

**Comment by kirrukirru** [comment]
This is still relevant. Currently, we don't have any control on the max memory needed by the vector tiles as the tiles cache keeps growing. @mourner
