### ISSUE TITLE
geojson-vt does not support certain point-only data sets

### ISSUE THREAD

**Issue by daniel-zillion** [mapbox/geojson-vt#41]
The tiling process fails when attempting to process geojson's containing geometries of type == 'Point'.

Is there any plan to support tiling points in the future or is this intentionally not included in the feature set of geojson-vt?

**Comment by mourner** [comment]
Points should be perfectly supported. Can you come up with a simple test case that fails for you?

**Comment by mourner** [comment]
There are even some tests for points: https://github.com/mapbox/geojson-vt/blob/master/test/fixtures/dateline.json

**Comment by daniel-zillion** [comment]
I should have clarified more:

The issue seems to be with exclusively point data sets, unless I am doing something wrong.

	//geo contains a geojson with 35000 features of type 'Point'
	
	 var opts = {
            maxZoom: 20, 
            tolerance: 5,
            extent: 4096, //changing this hasn't affected number of tiles
            buffer: 64,
            debug: 1,  
            indexMaxZoom: 0,    
            indexMaxPoints: 100000, // changing this hasn't either
        };
	
	var tileIndex = geojsonvt(geo, opts);


This does not produce any errors, but only yields one tile.
log output:
preprocess data: 21.701ms
index: maxZoom: 0, maxPoints: 10000000
features: 35895, points: 35895
generate tiles: 17.873ms
tiles generated: 1 {"z0":1}

Is there a usage error here? One tile only isn't a very practical approach for my use cases.

**Comment by mourner** [comment]
What did you expect? You're asking geojson-vt to generate tiles up to zoom 0 (!) and also not to tile below 100000 points in a tile. If you want to generate a bunch of tiles at once, change your index setting. If you want on-demand tiling, use `index.getTile`.
