### ISSUE TITLE
identifying geojson-vt features on leaflet

### ISSUE THREAD

**Issue by rishabhjain30** [mapbox/geojson-vt#42]
How can I associate click events with polygons from a polygon geojson which is rendered using geojson vt? I am trying to use leaflet to do that. Thanks for the help.

**Comment by mourner** [comment]
I don't understand your question. Can you clarify?

**Comment by rishabhjain30** [comment]
So, I have rendered a geojson to tiles using your tool. Now when I click on any of the features of the geojson, it should highlight that or associate a popup with that. How can I do that?

**Comment by mourner** [comment]
Sorry, I still have no clue what you have and what you want to do. Perhaps setting up a JSFiddle would help.

**Comment by rishabhjain30** [comment]
http://jsfiddle.net/b9yv5hm3/1/

So, in this I want to have a popup with polygon name whenever I click on any of the polygons.

**Comment by lksv** [comment]
+1

I am curious if it is possible somehow easy, or it is necessary implement yourself solution (probably based on [detection canvas element](https://stackoverflow.com/questions/16628184/add-onclick-and-onmouseover-to-canvas-element/30952993#30952993). Eventually I would be very grateful if you would give me an example/snippet.

**Comment by ConorCoakley** [comment]
+1 for me too re: this question. Geojson-vt is brilliant for rendering data, however it would be great to be able to interact with the data it renders. I have, for example, rendered a zip code geojson file using geojson-vt. I need to return info to the user on hover and click, and also need to be able to search and zoom to features. I haven't found any example of geojson-vt being used in this way. Is it possible (ideally using leaflet)?

**Comment by mourner** [comment]
It is possible (e.g. GeoJSON features in https://github.com/mapbox/mapbox-gl-js can be interactive, powered by geojson-vt), there's just no Leaflet example yet.

**Comment by ConorCoakley** [comment]
Thanks for the reply. Great to hear it's possible. I'm wondering, is leaflet interactivity easily implemented? Are the means to do this already in place in leaflet and it's associated plugins, and the geojson-vt leaflet plugin? Or would it requires changes to the geojson-vt leaflet plugin?
Thanks for your help and advise with this. Quite stuck with finding an effective way to render and interact with such a large dataset.

**Comment by mourner** [comment]
It would not require any changes on the geojson-vt or Leaflet side. Just needs some more glue code. Basically you would need to do hit detection (mouse coordinate against coordinates in geojson-vt geometries in a tile under the cursor) with a point-in-polygon algorithm.

**Comment by ConorCoakley** [comment]
Hmmm. Sounds like it might be beyond my capabilities. I'm a GIS data professional, but not a programmer by trade. Any pointers you could give would be greatly appreciated.

**Comment by reyemtm** [comment]
I am successfully using the [point in polygon](https://www.mapbox.com/mapbox.js/example/v1.0.0/point-in-polygon/) plugin to identify features, since the geojson is loaded already. I will add the live link once I finish the app. I am beginner in terms of javascript but this seems to do the trick. I am using the same method for searching the features using the leaflet search plugin.
```
var pikeParcels = L.geoJson();
var tileData = omnivore.topojson("pikeParcelsAll-simple-50.topojson", null, pikeParcels);
tileData.on('ready', function() {
  map.on('click', function(e) {
  if (point){
    map.removeLayer(point)
  }
   var x = e.latlng.lng;
   var y = e.latlng.lat;
   var layer = leafletPip.pointInLayer([x,y], pikeParcels, true);
   point = new L.circleMarker([y,x], {radius: 15, fill: false, opacity: 10}).bindPopup(layer[0].feature.properties.PINJOIN + '<hr>' + layer[0].feature.properties.OWNERLABEL);
   point.addTo(map);
   point.openPopup();
   point.on('popupclose', function() {
     map.removeLayer(point)
   });
 });
});
```

**Comment by ConorCoakley** [comment]
@reyemtm Are you doing this using the geojson-vt plugin?

**Comment by reyemtm** [comment]
Yes, I am using geojson-vt and the example from [here](http://bl.ocks.org/Sumbera/c67e5551b21c68dc8299) to add the tiles to the leaflet map. The geojson is loaded via the omnivore plugin as topojson, then added to an empty L.geoJson layer - which is not added to the map. To get it into the tiles I am using .toGeoJson(). You can view the working example at [www.ovrdc.org/apps/geojson-tiles](https://www.ovrdc.org/apps/geojson-tiles.html). 

The original parcel shapefile (22mb, 463K vertices, 24k features) was exported to geojson from ArcMap with the [esri2open](https://github.com/project-open-data/esri2open) plugin, then simplified (40%) using [mapshaper](http://www.mapshaper.org/) and exported as a topojson (5.5mb). 

This app is a test case to see if a county parcel viewer can be built without using a GIS server, which drives up the cost of such an application significantly. Frankly I'm amazed it works and at how fast it is, even on mobile. It is as fast if not faster than the OpenLayers 2/Geoserver app that is currently hosting the parcel viewer. Note that the app has all the plugins I use in all our web apps/maps loaded in the head. Only a handful of them are actually used in this app.

**Comment by ConorCoakley** [comment]
@reyemtm Thanks so much for sharing. This is definitely giving me a direction to try and go down.

**Comment by ConorCoakley** [comment]
@reyemtm Can I ask you one more question? I've tried using the omnivore plugin before and I can only get it to work if I pass a http link to it. When I try to pass a local file I get the dreaded cross origins error. How have you avoided that in your map?

**Comment by reyemtm** [comment]
Use a local server, I use Jekyll, do your testing on github using gh-pages
or use Firefox for local file support. Chrome does not like file data
sources, but chrome and a local server work just fine. On the website all
my hosted files come from our web server so no CORS issues.
