### ISSUE TITLE
Integration with D3/Leaflet

### ISSUE THREAD

**Issue by petulla** [mapbox/geojson-vt#45]
Are there any examples of integration with D3.js? 

I am following [this integration with Leaflet example](http://bl.ocks.org/sumbera/c67e5551b21c68dc8299), which seems intuitive enough, but am hoping to find something more baked out.

**Comment by mourner** [comment]
I'd love to see a d3 integration example, but this is not a geojson-vt issue.

**Comment by dferraz-daitan** [comment]
This should be brought up again...
