### ISSUE TITLE
Tiles not always immediately available

### ISSUE THREAD

**Issue by tcql** [mapbox/geojson-vt#46]
Using the natural earth country boundaries [from here](https://s3.amazonaws.com/geojson-please/naturalearth-3.3.0/ne_50m_admin_0_countries.geojson).

The first time I request some tiles, I get `null`, but if I wait, they return values. For example: 

```js
var fs = require('fs'),
  gvt = require('geojson-vt');

var c = gvt(JSON.parse(fs.readFileSync('ne_50m_admin_0_countries.geojson', 'utf8')));

console.log(c.getTile(15, 9379, 12533));

setTimeout(function () {
  console.log(c.getTile(15, 9379, 12533));
}, 5000);
```

**Comment by tcql** [comment]
actually, looks like the timeout isn't necessary here. You can just execute `getTile` twice in a row

**Comment by mourner** [comment]
Found the cause. It only happens for tiles which are children of solid clipped square tiles.

**Comment by mourner** [comment]
Published 2.1.8 with the fix.

**Comment by jfirebaugh** [comment]
@mourner Does this need to be ported to geojson-vt-cpp?

**Comment by mourner** [comment]
@jfirebaugh yes.
