### ISSUE TITLE
performance on mobile in leaflet stable with canvas layer

### ISSUE THREAD

**Issue by reyemtm** [mapbox/geojson-vt#50]
Any ideas in terms of tweaking the settings for better performance on mobile devices? I am using leaflet 0.7 with the canvas layer plugin. The tiles render fine on mobile, but when performing drastic zoom level changes or drastic panning, the tiles seem to hang/stop rendering. [Example](https://www.ovrdc.org/apps/geojson-tiles.html). This may be just a limit on the capabilities of mobile processors. I have tested on a samsung tab pro 8.4 and a one touch idol 3 both in chrome. If switching to leaflet-beta would help, I would need to figure out how to draw the tiles with the new grid layer. I don't really want to learn a new js library ie mapbox gl.

**Comment by mourner** [comment]
Try doing the loading / geojson-vt indexing step in a Web Worker instead of the main thread. If that doesn't help, then there's not much you can do — some mobile devices/browsers are pretty limited in processing power. This is also not a geojson-vt issue so I'm closing it.

**Comment by reyemtm** [comment]
Answering my own question - disabling various zoom functions/animations such as touch zoom and scroll zoom helped to improve performance.
