### ISSUE TITLE
Ability to Generate all possible tiles from the tileindex

### ISSUE THREAD

**Issue by awolden** [mapbox/geojson-vt#53]
I want to use this library to pre-generate a bunch of vector tiles and serve them from disk when a user requests it. Is there a way I can get a list of all possible tiles in tileIndex for pre-generation?

**Comment by mourner** [comment]
You just run geojson-vt with `indexMaxZoom` set to `maxZoom` and `indexMaxPoints` set to 0. It'll generate all possible tiles, with all coords stored in `tileIndex.tileCoords`.
