### ISSUE TITLE
Reverse functionality vt-geojson

### ISSUE THREAD

**Issue by dbauszus** [mapbox/geojson-vt#61]
Is there a library which offers a reverse of the functionality?

Is it possible to tweak this library to reverse the stream?

I am planning to build a vector tile server and render the tiles in a leaflet application. I would like to integrate an export as geoJSON functionality. It's easy enough to request the geoJSON directly from the server but it would be quicker to just create the export in the browser since the data is already available locally.

Thanks for any pointers.
Dennis

**Comment by mourner** [comment]
Do you mean stitching tiles back together? Or just converting tiles to GeoJSON format?

**Comment by dbauszus** [comment]
Converting the tiles which are rendered in the viewport into a single geojson. First stitching together and then converting.

**Comment by mourner** [comment]
No, this is technically extremely difficult and way out of scope for this library.

**Comment by lksv** [comment]
If I understand the question correctly, IMHO you can use following lines in you "drawing" callback:
```
 tile =  geojsonvtInstance.getTile(params.tilePoint.z, params.tilePoint.x, params.tilePoint.y);
 var features = tile ? tile.features : []
```

Notice that you will have slightly  more GeoJSON features in the *features* variable i.e. It will contain all features in rendered tiles.

(I am definitely not geojson-vt, leaflet, get-* expert, so maybe my answer could be wrong.)

**Comment by mourner** [comment]
@dbauszus to be clear, converting to GeoJSON is very easy. It's the stitching that is extremely challenging algorithmically.

**Comment by createthis** [comment]
@mourner hey, sorry to necro this issue, but I'm curious how to convert an individual tile to geojson. You say it's very easy? What's the procedure?

**Comment by mourner** [comment]
@createthis it should be very similar to this code https://github.com/mapbox/vector-tile-js/blob/master/lib/vectortilefeature.js#L129

**Comment by createthis** [comment]
@mourner Can vector-tile-js be used to perform the conversion directly, or does it need a custom written method?

**Comment by mourner** [comment]
You would have to manually write code specifically for geojson-vt. vector-tile-js is for pbf vector tiles, although geojson-vt has a similar tile format.

**Comment by createthis** [comment]
That's what I thought. Thanks!

**Comment by createthis** [comment]
@mourner I'm sure there are still some bugs in here, but it seems to be mostly working with my example data and it's based on the code you linked, with dependencies fixed for geojson-vt:
https://jsfiddle.net/070m3jk7/

Maybe that will help someone else in the future looking for the same functionality. Posterity and all that.
