### ISSUE TITLE
the grid data can't generate tile?

### ISSUE THREAD

**Issue by lzxue** [mapbox/geojson-vt#68]
my code

      var tileIndex = geojsonvt(geojsondata, {

     maxZoom: 10, // max zoom to preserve detail on

     tolerance:3, // simplification tolerance (higher means simpler)

     extent: 4096, // tile extent (both width and height)
     buffer: 64, // tile buffer on each side

     debug: 2, // logging level (0 to disable, 1 or 2)

     indexMaxZoom: 0, // max zoom in the initial tile index

     indexMaxPoints: 1000, // max number of points per tile in the index
      solidChildren: true  });`

my data is  equidistant grid ,but i getTile return null,

I drag my geojson data to the page  http://mapbox.github.io/geojson-vt/debug/    it also not the tiles.
this is my data https://github.com/lzxue/geojson-map-china/blob/master/huinongcaoyendvi.json

**Comment by ChandlerBuck** [comment]
Is your problem related to the zoom level of the map? That seems to be the issue with my project at the moment. If the zoom level is greater than 14 I get: TypeError: Uncaught error: Cannot read property 'features' of null

**Comment by mourner** [comment]
@lzxue try disabling simplification — I think geojson-vt throws out lines that are too small. In any case, I think your data doesn't make sense on a map. You have lines with coordinates like `[120.664973,43.781918],[120.66517300000001,43.781918]`, which are about the length of an atom.
