### ISSUE TITLE
Discrepancy between tile.features and tile.source

### ISSUE THREAD

**Issue by t-sch** [mapbox/geojson-vt#71]
Hi,
in my prototype I have a discrepancy between the feature count in tile.features and tile.source. Tile.numFeatures has the same number as tile.source.length.
This happens only in some of the tiles, some others contain what I expected.
Is there an Explanation?
Regards,
-Thomas

**Comment by mourner** [comment]
`tile.features` contains simplified features, with some of the features thrown out because they're too small. https://github.com/mapbox/geojson-vt/blob/master/src/tile.js#L55

**Comment by t-sch** [comment]
Shouldn't the features stay, maybe with empty geometry, so the indices run parallel?

**Comment by mourner** [comment]
No.
