### ISSUE TITLE
How can I calc back tile geometry coordinates?

### ISSUE THREAD

**Issue by t-sch** [mapbox/geojson-vt#72]
What's the formula to calc back tile geometry coordinates (extent+-buffer range) to [0..1] Mercator coordinates provided I give the tile address?

**Comment by mourner** [comment]
Take [this function](https://github.com/mapbox/geojson-vt/blob/master/src/transform.js#L37-L41) and make up an inverse of that.

**Comment by t-sch** [comment]
Thanks that worked.
