### ISSUE TITLE
MapBox Vector Tile v2 support

### ISSUE THREAD

**Issue by clouddie** [mapbox/geojson-vt#75]
Hi, just a quick question, does geojson-vt support mapbox vector tile v2 specification ?

I get a warning in the console `Vector tile source "mysource" layer "mylayer" does not use vector tile spec v2 and therefore may have some rendering errors` from mapbox-gl-js. I can still see the rendered features on the map.

My layer is composed of a single linestring `'LINESTRING(114.199297 22.330566,114.195756 22.3272910, 114.1945981 22.3214950)'`, is it a geometry error ? (I am asking this as my other point layers are totally fine, not triggering any mapbox vector tile v2 warning)

**Comment by mapsam** [comment]
Hey @clouddie - which version of geojson-vt are you using? [`2.2.0`](https://github.com/mapbox/geojson-vt#220-jun-9-2016) suggests winding order rendering was updated to support the v2 spec.

**Comment by clouddie** [comment]
Hi, am using v 2.4.0, but as you say it should support vector tile v2.
Maybe my geojson isn't right...

**Comment by mourner** [comment]
Are you also using something like `vt-pbf`?

**Comment by clouddie** [comment]
Yes, the vector tile output of geojson-vt is then fed into vt-pbf.

Le 14 déc. 2016 1:08 PM, "Vladimir Agafonkin" <notifications@github.com> a
écrit :

**Comment by mourner** [comment]
I think this is an issue with `vt-pbf` not encoding a `version` field in the layer. Let's move over the ticket there.

**Comment by clouddie** [comment]
Ok thanks !

Le 14 déc. 2016 1:18 PM, "Vladimir Agafonkin" <notifications@github.com> a
écrit :

**Comment by gmaclennan** [comment]
See https://github.com/mapbox/vt-pbf/issues/12#issuecomment-270631200 for a possible (untested) solution.
