### ISSUE TITLE
Don't understand how it works

### ISSUE THREAD

**Issue by supernul** [mapbox/geojson-vt#76]
Hi,

I try to display a lots of polygons from a Geojson variable :

```
var dataLayer = new L.Proj.geoJson(data); // my data is in EPSG:2145 and 
var dataJson = dataLayer.toGeoJSON(); // to convert in GeoJSON
var tileIndex = new geojsonvt(dataJson); // to create vectorTile
```

but after I don't understand what to do to display tiles. I don't find a simple example. All examples make a lot of things. The simpliset I found is http://bl.ocks.org/sumbera/c67e5551b21c68dc8299

Thank you.

**Comment by reyemtm** [comment]
geojson-vt is just for converting geojson on the fly in the browser to vector tiles. You need your own function to then display these on say a leaflet map. See the ovrdc parcel viewer [map](http://ovrdc.github.io/parcel-viewer/#11/38.8092/-82.3391) and [code](https://github.com/ovrdc/parcel-viewer/blob/gh-pages/_layouts/map.html#L564), based on the sumbera example, for a real-world implementation of this.

**Comment by mapsam** [comment]
Indeed, thanks for those examples @reyemtm! Similarly, geojson-vt is what mapbox-gl-js uses for creating GeoJSON sources on the fly. Here's the [dependency](https://github.com/mapbox/mapbox-gl-js/blob/1926aa502302bf82b606836f0eac709d3e45690b/package.json#L21) and the [usage](https://github.com/mapbox/mapbox-gl-js/blob/20783c7b0d68d42dc10d7589e22dc9ac770cbd5b/js/source/geojson_worker_source.js).
