### ISSUE TITLE
outer is missing in the resulting geometry

### ISSUE THREAD

**Issue by Sumbera** [mapbox/geojson-vt#79]
it is impossible to determine outer or inner rings in multi polygon case, added outer to the resulting geometry #78

**Comment by mourner** [comment]
geojson-vt encodes outer/inner rings through signed area according to the vector tile specification v2. See https://github.com/mapbox/vector-tile-spec/tree/master/2.1#4344-polygon-geometry-type

**Comment by Sumbera** [comment]
... so to get this info I need to calculate the area first and check its sign ?  really ?

**Comment by mourner** [comment]
@Sumbera yes. This is not ideal obviously, but was the only option that didn't require doing a major breaking change to the vector tile specification. We want to address that with the next revision of the spec, tracked in https://github.com/mapbox/vector-tile-spec/issues/77.
