### ISSUE TITLE
topojson support

### ISSUE THREAD

**Issue by kodonnell** [mapbox/geojson-vt#81]
Firstly, quoting @mourner from [here](https://github.com/mapbox/geojson-vt/pull/48#issuecomment-166973804):

> I would not want to include any TopoJSON-specific code in the geojson-vt source. It's easy enough to convert to GeoJSON first and then serve it to geojson-vt

I understand and agree with that - except for performance considerations. Without knowing anything about the internals of geojson-vt, my suspicion (completely untested) is that topojson may be (considerably?) faster overall, largely because

1. file sizes are smaller (can be more than an order of magnitude) so it can be a lot faster to load (and uses less memory)
2. e.g. arc's aren't duplicated on the boundaries between polygons, so less processing required?

Another untested claim: it might even be faster loading topojson and converting to geojson than loading geojson in the first place.

Admittedly, there are only likely to be noticeable differences in large polygon files etc. - and that may be outside the common use case.

**Comment by mourner** [comment]
Thanks for the report! This is a reasonable suggestion. However, I'm not willing to support TopoJSON internally in GeoJSON-VT for two more reasons:

1. It will considerably increase implementation complexity, placing more burden on me as a maintainer.
2. GeoJSON-VT is already fast enough for most practical use cases, so there's no incentive to improve it further while sacrificing code simplicity.

If you still want to explore this feature, I encourage you to fork the repo and attempt implementing this. Would love to see some benchmarks!

**Comment by kodonnell** [comment]
Thanks @mourner - both good reasons. No promises, but a fork does sound like something within my abilities, and quite fun.
