### ISSUE TITLE
Switch to flat representation of geometry for performance

### ISSUE THREAD

**Issue by mourner** [mapbox/geojson-vt#85]
Currently, GeoJSON-VT stores all points as arrays `[[x, y, z], [x, y, z], ...`, and each feature has a separate array of nested point/ring arrays. To significantly improve performance, memory usage and reduce the occurrences of GC, we should instead try storing all intermediate and final representations of geometries in flat arrays (`[x, y, z, x, y, z, ...]`) — ideally, one per tile, with individual features referencing it with indices. Ring structure could be represented with length prefixes, like we do in geobuf, e.g. `[num_rings, num_ring1_points, x, y, z, ...]`. cc @jfirebaugh

**Comment by mourner** [comment]
Hacked a bit on this today. Switching the [convert](https://github.com/mapbox/geojson-vt/blob/master/src/convert.js) stage of indexing (including Mercator projection, bbox/area/length calculation and Douglas-Peucker simplification) to flat arrays of numbers takes 40% less time — a huge performance win! We should definitely do this.

**Comment by mourner** [comment]
WIP in [flat-geom branch](https://github.com/mapbox/geojson-vt/compare/flat-geom)

**Comment by theKashey** [comment]
What about not having a single array for [x,y,z], but split everything into 3 different arrays(channels)?
> [x,x,x] + [y,y,y] + [z,z,z] + ([u,u] + [v,v])
It can provide some benefits from data "locality" point of view, and also more friendly for SIMD (one day, one day).
The only big drawback I see here - this format is a bit better for an array of points, but not very suitable for a single point.

**Comment by mourner** [comment]
@theKashey yeah, it will be inefficient for single point features and any kind of small geometries with only a few points, since there will be three arrays instead of one. We should also avoid optimizing for something that may not even see the light of day (I've heard SIMD is going to be implemented as a part of WebAssembly and ditched as a JS API).

**Comment by theKashey** [comment]
SIMD is already here. But not providing a better experience, yet. Especially due to JS memory model.
You are moving in the right direction. Good luck.

**Comment by mourner** [comment]
@theKashey the [MDN SIMD page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SIMD) has the following statement:

> SIMD.js has been taken out of active development in TC39 and removed from Stage 3. It is not being pursued by web browsers for implementation anymore. SIMD operations exposed to the web are under active development within WebAssembly, with operations based on the SIMD.js operations.

**Comment by theKashey** [comment]
😭

**Comment by mourner** [comment]
Converting everything to a single flat array turned out to be too involved, but flattening only one level (rings) brings almost the same perf benefits while being much simpler to implement: `[[x, y, z, x, y, z, ...], [x, y, z, x, y, z, ....]]`.
