### ISSUE TITLE
Simplify causes adjacent polygons cross

### ISSUE THREAD

**Issue by dongli** [mapbox/geojson-vt#89]
I used the following default parameters:

```
{
  maxZoom: 14,            // max zoom to preserve detail on
  indexMaxZoom: 5,        // max zoom in the tile index
  indexMaxPoints: 100000, // max number of points per tile in the tile index
  solidChildren: false,   // whether to tile solid square tiles further
  tolerance: 3,           // simplification tolerance (higher means simpler)
  extent: 4096,         // tile extent
  buffer: 64,             // tile buffer on each side
  debug: 0                // logging level (0, 1 or 2)
}
```
and found the adjacent polygons at the first level cross each other:
![image](https://user-images.githubusercontent.com/367959/32990581-da6ce09c-cd66-11e7-969f-e0d441099b31.png)
Any idea? Thanks!

EDIT:

When I set `tolerance` to 0 for disabling simplify, the map is almost empty.

**Comment by dongli** [comment]
I found Visvalingam algorithm is better than Douglas-Peucker as shown in [here](https://github.com/mbloch/mapshaper/wiki/Simplification-Tips)

**Comment by mourner** [comment]
Since outlines are simplified independently, there's no way to fix this fully — the only way I know is processing the outlines topologically, like [TopoJSON](https://github.com/topojson/topojson), finding shared parts of the polygon and simplifying them separately. GeoJSON-VT won't go that route because it's too expensive.

**Comment by dongli** [comment]
Thanks for explanation! I am going to create tiles in the backend, so it is not the design scenario of GeoJSON-VT.

**Comment by reyemtm** [comment]
I realize this is closed, but wanted to add a few thoughts and examples. The only way I could remedy unwanted simplification effects (on polygons with only four vertices) was to generate tiles up to zoom level 20, and even still there are small simplification artifacts. Here are some samples for future reference:

![](https://cozgis.netlify.com/assets/img/zoom20.JPG)
![](https://cozgis.netlify.com/assets/img/zoom22.JPG)

**Comment by mourner** [comment]
@reyemtm what you experience is likely not simplification, but rounding to integer coordinates. To remedy that, you need to increase `extent` — e.g. going from 4096 to 16384 is equivalent to bumping max zoom by 2.

**Comment by reyemtm** [comment]
I'll try that, thanks for the info. Will reply with an update.
