### ISSUE TITLE
circles with a large radius are clipped off

### ISSUE THREAD

**Issue by kkdd** [mapbox/geojson-vt#96]
Hello,
I realize that circles with a large radius are clipped off when using geojson-vt shown as the following example:

![circle](https://user-images.githubusercontent.com/5372642/37969471-cba00c88-320b-11e8-988c-4cbcbec8203a.jpg)

Is there any method to fix this phenomenon?

**Comment by mourner** [comment]
Can you show the exact GeoJSON that produces the result above?

**Comment by kkdd** [comment]
Sorry.
I have just realized that this is not related to geojson-vt.
